Add report generation

diff --git a/.github/workflows/go.yml b/.github/workflows/go.yml
--- a/.github/workflows/go.yml
+++ b/.github/workflows/go.yml
@@ -7,7 +7,6 @@ on:
     branches: [ "main" ]
 
 jobs:
-
   build:
     runs-on: ubuntu-latest
     steps:
@@ -22,4 +21,13 @@ jobs:
       run: go mod download
 
     - name: Test
-      run: make test
+      env:
+        AISERA_PASSWORD: ${{ secrets.AISERA_PASSWORD }}
+        AISERA_USERNAME: ${{ secrets.AISERA_USERNAME }}
+      run: env && make test
+
+    - name: Publish Test Report
+      uses: mikepenz/action-junit-report@v3
+      if: success() || failure() # always run even if the previous step fails
+      with:
+        report_paths: '**/report.xml'
